version: '3'

services:
  server:
    build: ./server
    command: python manage.py runserver localhost:8000
    ports:
      - 8000:8000
  clent:
    build: ./client
    command: npm run build
    ports:
      - 5000:5000
    depends_on:
      - server
