# Generated by Django 4.0.4 on 2022-04-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='Дата')),
                ('title', models.CharField(db_column='Название', max_length=100)),
                ('amount', models.IntegerField(db_column='Количество')),
                ('distance', models.DecimalField(db_column='Расстояние', decimal_places=2, max_digits=11)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
